// backend/domain/metricGlossary.js
//
// One entry per metric any tool can return. Every `definition` is
// transcribed from the doc comment above the source function in
// derived.js / definitions.js — not paraphrased from memory.

const metrics = [
  {
    metric: 'accountability',
    label: 'Accountability Score',
    definition: 'Per-entity score from RACI links, averaged across entities. Scores 100 when an entity has separate Responsible and Accountable people, 60 when one person holds both roles, 40 when it has only one of the two, and 0 when it has neither. Consulted/Informed links are recorded but do not affect the score.',
    range: '0-100 per entity, averaged org-wide',
    authored: true,
    authoredNote: 'The point values (100/60/40/0) are a chosen scoring rubric, not a measured quantity.',
    computedIn: 'backend/domain/derived.js :: accountability()',
    decisions: [],
  },
  {
    metric: 'collaboration',
    label: 'Collaboration Score',
    definition: 'Blends adoption (usage engagement across employees and agents) with independence (inverse of dependency concentration). High adoption combined with high dependency means a bottleneck, not collaboration, so the two are blended rather than added.',
    range: '0-100',
    authored: true,
    authoredNote: 'Usage weights, the adoption-saturation point, and the 0.6/0.4 adoption-vs-independence blend are chosen design values.',
    computedIn: 'backend/domain/derived.js :: collaboration()',
    decisions: [],
  },
  {
    metric: 'predictiveRisk',
    label: 'Predictive Risk Score',
    definition: "Per-agent score built by summing penalty points from independently observable conditions: single owner with no backup (30), high dependency count (25 for 3+, 12 for 1-2), critical workflow dependency (27), undocumented knowledge (18), unstable status (25 failed / 10 inactive), and intrinsic recorded risk (20 critical / 12 high). isEmergingThreat flags when the computed score lands in a higher band than the agent's own recorded risk label.",
    range: '0-100, banded LOW/MEDIUM/HIGH/CRITICAL at 35/55/75',
    authored: true,
    authoredNote: 'Each risk factor and its point value (RISK_FACTORS) is a chosen design value, not a measured statistic.',
    computedIn: 'backend/domain/derived.js :: predictiveRisk()',
    decisions: [],
  },
  {
    metric: 'humanDependencyRisk',
    label: 'Human Dependency Risk',
    definition: "Per-employee score dominated by the mean predicted risk of the agents they own. Adds critical-workflow load and tool-backup coverage as fractional factors (not raw counts), so owning many workflows doesn't mechanically inflate the score. Deliberately avoids double-counting workflow backup coverage, since that is already priced into predictiveRisk's single-owner factor.",
    range: '0-100',
    authored: true,
    authoredNote: 'Combines multiple weighted factors chosen by the team; not a direct measurement.',
    computedIn: 'backend/domain/derived.js :: humanDependencyRisk()',
    decisions: [],
  },
  {
    metric: 'knowledgeConcentration',
    label: 'Knowledge Concentration',
    definition: "Per-employee criticality-weighted share of org-wide assets (agents + workflows + tools) one person owns. Ported verbatim from the former frontend concentrationScore logic. Distinct from the per-person absolute knowledgeRiskScore used elsewhere, which is not normalized against org totals.",
    range: '0-100, tiered LOW/MEDIUM/HIGH/CRITICAL at 30/55/90',
    authored: true,
    authoredNote: 'The concentration weight table (critical=4 ... unknown=1) and tier bands are chosen values, carried over unchanged from the original frontend design.',
    computedIn: 'backend/domain/derived.js :: knowledgeConcentration()',
    decisions: [],
  },
  {
    metric: 'orgMemory',
    label: 'Institutional Memory Health Score (IMHS)',
    definition: 'Classifies every asset (agent/workflow/tool) into PRESERVED / AT_RISK / VULNERABLE / LOST based on whether it has an owner, is documented, and has a backup. IMHS is a weighted percentage: preserved counts full, vulnerable half, at-risk quarter, lost zero.',
    range: 'IMHS 0-100',
    authored: true,
    authoredNote: 'The IMHS weights (1.0 / 0.5 / 0.25 / 0) are a chosen scoring convention.',
    computedIn: 'backend/domain/derived.js :: orgMemory()',
    decisions: [],
  },
  {
    metric: 'assetContinuity',
    label: 'Asset Continuity',
    definition: "Per-asset disruption-survival status (LOST/FAILS/DEGRADED/SURVIVES, based on owner/backup/documentation and whether the asset is high-stakes) plus a governance score starting at 100 with deductions of 40 (no owner), 25 (no backup), 20 (undocumented). Ported verbatim from the former frontend continuity-risk calculation; the UI labels this an estimate, distinct from the real M18/M19 continuity/governance modules.",
    range: 'governance score 0-100',
    authored: true,
    authoredNote: 'Survival rule and governance deductions are chosen values (D-61), carried over unchanged from the prior frontend heuristic.',
    computedIn: 'backend/domain/derived.js :: assetContinuity()',
    decisions: ['D-61'],
  },
  {
    metric: 'executiveMemory',
    label: 'Executive Memory Signals',
    definition: "Surfaces patterns worth executive attention: recurring workflow failures, hero risk (a person carrying 2+ critical assets with no named backup), and flagged/negative decisions. Each item gets a 0-1 relevanceScore so a caller can take a top-N without needing to know what the type labels mean.",
    range: 'relevanceScore 0-1 per item',
    authored: true,
    authoredNote: 'The hero-risk threshold (2 assets) and severity ranking weights are chosen values.',
    computedIn: 'backend/domain/derived.js :: executiveMemory()',
    decisions: [],
  },
  {
    metric: 'org_score',
    label: 'Organizational Intelligence Score (OIS)',
    definition: 'Weighted composite of three pillars: Governance Intelligence (0.35), Management Intelligence (0.35), Data Intelligence (0.30). Data is weighted slightly lower because its inputs are currently the thinnest in the data set.',
    range: '0-100',
    authored: true,
    authoredNote: 'Pillar weights are an explicit, changeable design choice — the source comment names this as the one place to edit if the weights are wrong for the business.',
    computedIn: 'backend/domain/derived.js :: pillars()',
    decisions: [],
  },
  {
    metric: 'GI',
    label: 'Governance Intelligence (GI) Pillar',
    definition: 'One of three pillars composing org_score (weight 0.35). Returns its own components so a reader can see which part is dragging the pillar down rather than being handed a bare number.',
    range: '0-100',
    authored: true,
    authoredNote: 'Pillar weight (0.35) is a chosen value, part of PILLAR_WEIGHTS.',
    computedIn: 'backend/domain/derived.js :: pillars()',
    decisions: [],
  },
  {
    metric: 'MI',
    label: 'Management Intelligence (MI) Pillar',
    definition: 'One of three pillars composing org_score (weight 0.35). Returns its own components so a reader can see which part is dragging the pillar down rather than being handed a bare number.',
    range: '0-100',
    authored: true,
    authoredNote: 'Pillar weight (0.35) is a chosen value, part of PILLAR_WEIGHTS.',
    computedIn: 'backend/domain/derived.js :: pillars()',
    decisions: [],
  },
  {
    metric: 'DI',
    label: 'Data Intelligence (DI) Pillar',
    definition: 'One of three pillars composing org_score (weight 0.30, deliberately lower than the other two because its inputs — truth_claims — are currently the thinnest in the data set).',
    range: '0-100',
    authored: true,
    authoredNote: 'Pillar weight (0.30) is a chosen value, part of PILLAR_WEIGHTS.',
    computedIn: 'backend/domain/derived.js :: pillars()',
    decisions: [],
  },
  {
    metric: 'decisionQuality',
    label: 'Decision Quality',
    definition: 'Share of recorded decisions that did not turn out badly. Decisions still awaiting an outcome are excluded rather than counted as successes, since a pending decision is not evidence of good judgement.',
    range: '0-100 (%)',
    authored: false,
    computedIn: 'backend/domain/derived.js :: decisionQuality()',
    decisions: [],
  },
  {
    metric: 'orgHealth',
    label: 'Organizational Health (current month)',
    definition: "This month's org health snapshot, matching the org_health_snapshots time-series columns. Combines the accountability and predictive-risk results with an incident-load penalty (25 points per workflow failure). History cannot be recomputed, since the Knowledge Graph has no time dimension — existing prior months remain seed data.",
    range: '0-100 per sub-score',
    authored: true,
    authoredNote: 'The incident-load penalty (25 points per failure) is a chosen constant, tuned so a healthy estate stays in the 80s and a struggling one lands near 50.',
    computedIn: 'backend/domain/derived.js :: orgHealth()',
    decisions: ['D-21'], // referenced by assetContinuity's comment as orgHealth's own header decision — verify against orgHealth's full header comment directly
  },
  {
    metric: 'orgHealthByDepartment',
    label: 'Organizational Health by Department',
    definition: "Runs orgHealth() once per department using a department-filtered copy of the data bundle. Has no separate formula of its own — it reuses orgHealth's exact definition and weighting, scoped to one department at a time.",
    range: '0-100 per sub-score, per department',
    authored: true,
    authoredNote: 'Inherits orgHealth\'s authored weighting; introduces no new judgment of its own.',
    computedIn: 'backend/domain/derived.js :: orgHealthByDepartment() (delegates to orgHealth())',
    decisions: [],
  },
  {
    metric: 'departmentExposure',
    label: 'Department Exposure',
    definition: "How exposed a department is to disruption — a distinct question from orgHealthByDepartment's 'how healthy is it overall'. Equal thirds: documentation coverage, backup coverage, and an incident-free score scoped to that department's own workflow failures. incidentRiskLevel bands the inverse of the exposure score using the same 40/65/85 boundaries used everywhere else in the product.",
    range: '0-100',
    authored: true,
    authoredNote: "Explicitly marked AUTHORED in the source comment: not a recovery of an existing formula — the frozen table's seed rows carry no derivation.",
    computedIn: 'backend/domain/derived.js :: departmentExposure()',
    decisions: [],
  },
  {
    metric: 'entityCriticality',
    label: 'Entity Criticality',
    definition: "Resolves an entity's criticality level. For agents and workflows, reads their own recorded risk column directly. Platforms carry no criticality column, so a platform's criticality is the highest criticality among the knowledge assets recorded about it — one critical piece of knowledge about a tool makes the tool critical. A platform with no knowledge assets reports UNKNOWN rather than a default level.",
    range: "'critical' | 'high' | 'medium' | 'low' | 'unknown'",
    authored: true,
    authoredNote: 'Measured (a direct column read) for agents and workflows; a judgment-based derivation for platforms, since nothing in the source data defines a platform\'s criticality directly.',
    computedIn: 'backend/domain/definitions.js :: entityCriticality()',
    decisions: [],
  },
  {
    metric: 'edgeCriticality',
    label: 'Dependency Edge Criticality',
    definition: "Criticality of a dependency EDGE (not the entity itself), read from dependencies.dependency_type. Kept deliberately separate from entityCriticality, since 'this link is critical' and 'this thing is critical' are different claims.",
    range: "'critical' | 'high' | 'medium' | 'low' | 'unknown'",
    authored: false,
    computedIn: 'backend/domain/definitions.js :: edgeCriticality()',
    decisions: [],
  },
  {
    metric: 'spofVerdict',
    label: 'Single Point of Failure Verdict',
    definition: "Classifies an asset into one of four outcomes: spof (sole owner, no backup, above the criticality threshold), orphaned (nobody owns it — a worse finding than a sole owner, kept separate rather than folded into not_spof), not_evaluable (criticality unmeasured), or not_spof.",
    range: "'spof' | 'orphaned' | 'not_evaluable' | 'not_spof'",
    authored: true,
    authoredNote: 'The SPOF criticality threshold is a chosen cutoff, not a measured value.',
    computedIn: 'backend/domain/definitions.js :: spofVerdict()',
    decisions: [],
  },
  {
    metric: 'coverage',
    label: 'Field Coverage',
    definition: 'Share of a population of rows that actually carries a given field/signal, used to decide whether a score is safe to compute at all.',
    range: '0-1',
    authored: true,
    authoredNote: 'The 0.5 coverage threshold (D-10) below which a score is treated as unsafe to compute is a chosen cutoff.',
    computedIn: 'backend/domain/definitions.js :: coverage()',
    decisions: ['D-10'],
  },
]

function getMetricDefinition(metricName) {
  return metrics.find((m) => m.metric === metricName) || null
}

module.exports = { metrics, getMetricDefinition }